### PR TITLE
fix js error

### LINKED ISSUE #49: JS error
image

### PR DESCRIPTION
**Pull request by bshaoatenvisiodotcom**

### CODE REVIEW

File: src/index.jsx [hunk 1]
```diff
@@ -243,18 +248,23 @@ export default class FormulaBar extends Component {
     );
     let valueLast;
     let insideFunc = false;
-
-    if (valueTail.match(/[A-Za-z]+\d*$/g)) {
-      [valueLast] = valueTail.match(/[A-Za-z\d]+$/g).reverse();
-    } else if (valueTail.match(/[A-Za-z]+\d*\([^\)]*/g)) {
+    const valueLastMatch1 = valueTail.match(/[A-Za-z\d]+$/g);
```
Comment (ed-wong) [inline src/index.jsx:251]: It seems like this code should be the same as `suggestionWorker` but it's a little bit different.

It would be better to be able to extract it out.

**Review by ed-wong — APPROVED** [review]
Left a comment about something small that doesn't need to be changed right now. Tested and it seems ok.
